### ISSUE TITLE
Please license this wrapper under open source licence

### ISSUE THREAD

**Issue by irnc** [wojtkowiak/meteor-react-intl#2]
Could you please license your wrapper using any open source licence, e.g. MIT?

I would like to use it with recent Meteor and React 0.14, what requires to switch this wrapper to react-intl v2.0.0 (v2.0.0-beta-1 as of now).

**Comment by wojtkowiak** [comment]
I've bumped react-intl to 2.0.0-pr-3 and added LICENSE file.

**Comment by irnc** [comment]
Thanks a lot!
